backend:
  replicaCount: 2
  image:
    repository: aniketsharma05/fintrack-backend
    tag: "v1"
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

frontend:
  replicaCount: 2
  image:
    repository: aniketsharma05/fintrack-frontend
    tag: "v6"
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30080