name: FinTrack CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/**'

jobs:
  lint-and-validate:
    name: Helm & YAML Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint charts/fintrack/

  security-scan:
    name: DevSecOps Filesystem Scan
    runs-on: ubuntu-latest
    needs: lint-and-validate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. File System Scan (Catches misconfigurations and Helm vulnerabilities)
      - name: Run Trivy Vulnerability Scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'